name: cashier_mobile
description: "تطبيق إلكترو كاشير لإدارة معارض ومخازن الأجهزة الكهربائية والمنزلية والمزامنة السحابية"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.3
  flutter_local_notifications: ^22.3.1
  url_launcher: ^6.3.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
