<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>POS.Desktop</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>POS Supermarket Cashier System</ApplicationTitle>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.90" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0-preview.2.25164.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0-preview.2.25163.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POS.Licensing\POS.Licensing.csproj" />
  </ItemGroup>

</Project>
