<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sales.Domain\Sales.Domain.csproj" />
    <ProjectReference Include="..\Inventory.Domain\Inventory.Domain.csproj" />
    <ProjectReference Include="..\Shifts.Domain\Shifts.Domain.csproj" />
    <ProjectReference Include="..\Settings.Domain\Settings.Domain.csproj" />
    <ProjectReference Include="..\POS.Shared.Application\POS.Shared.Application.csproj" />
    <ProjectReference Include="..\POS.Shared.Domain\POS.Shared.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
  </ItemGroup>

</Project>
